/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'srramas' at '7/4/17 9:24 AM' with Gradle 3.0
 *
 * @author srramas, @date 7/4/17 9:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
